name: GitHub Actions Security Analysis with zizmor

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: {}

jobs:
  lint-workflows:
    name: Lint GitHub workflows
    runs-on: ubuntu-24.04 # pinned for determinism
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa
        with:
          advanced-security: false
          min-severity: medium
          min-confidence: medium

      - name: Validate workflows and actions
        uses: mpalmer/action-validator@c994f427b7c42cd5ecb1bc9315cb91c3d7d72e3d # v0.9.0
        with:
          version: 0.9.0
